--- #YAML:1.0
name:               Tk-Canvas-Point
version:            0.06
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    File::Spec:  0
    Tk::MMutil:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  git://github.com/eserte/tk-canvas-point.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
